- name: Print linux distribution and version
  hosts: all
  remote_user: itadmin
  tasks:
    - name: cat /etc/issue
      shell: cat /etc/issue
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      register: etc_issue
    - debug: msg="{{etc_issue.stdout_lines}}"
